#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May 24 11:07:08 2020

@author: andresparrado
"""

from Bank import *

def test(): #this test function should throw an
    user = BankUser("Joe");
    user.addAccount(AccountType.SAVINGS);
    user.addAccount(AccountType.CHECKING);
    user.deposit(AccountType.SAVINGS, 10);
    user.deposit(AccountType.CHECKING, 100);
    
    print('balance in savings is {}'.format(user.getBalance(AccountType.SAVINGS)))
    print('balance in checking is {}'.format(user.getBalance(AccountType.CHECKING)))
    
    try:
        user.addAccount('something random')
    except Exception as e:
        print(e);
    
    try:
        user.withdraw(AccountType.SAVINGS, 1000); #this should throw an Exception or Error
    except Exception as e:
        print(e); #print the message for the Exeption
        
    try:
        user.withdraw(AccountType.SAVINGS, -10); #this should throw an Exception or Error
    except Exception as e:
        print(e); #print the message for the Exeption
    
    try:
        user.addAccount(AccountType.SAVINGS); #this should throw an Exception or Error
    except Exception as e:
        print(e); #print the message for the Exeption
    
    try:
        user.addAccount(AccountType.CHECKING); #this should throw an Exception or Error
    except Exception as e:
        print(e); #print the message for the Exeption
        
    print(user) #this should print the str of the class
    
test();


